CNV/ODF operator install

diff --git a/on_premise/Makefile b/on_premise/Makefile
--- a/on_premise/Makefile
+++ b/on_premise/Makefile
@@ -7,7 +7,7 @@ export PARENT_PATH = $(shell dirname $(MAIN_PATH))
 export MAIN_PATH = $(shell pwd)
 
 # Targets
-.PHONY: install-config cluster destroy help operator version test
+.PHONY: install-config cluster destroy help operator operator_common operator_odf operator_cnv version test
 
 cluster:
 	@echo "Checking environment setup..."
@@ -25,17 +25,29 @@ cluster:
 	@chmod +x $(MAIN_PATH)/login.sh
 	@bash $(MAIN_PATH)/login.sh
 
-operator:
+operator_common:
 	@if [ ! -f "$(MAIN_PATH)/environment_variables.sh" ]; then \
 		echo "Environment script $(MAIN_PATH)/environment_variables.sh not found! Please ensure it exists."; \
 		exit 1; \
 	fi
+	@git pull
+
+operator: operator_common
 	@read -p "Did you add the required ODF disks (3 disks per worker)? [y/N] " confirm && if [ "$$confirm" != "y" ]; then \
 		echo "Please add the disks before proceeding."; \
 		exit 1; \
 	fi
-	@git pull
 	@bash -c "source $(MAIN_PATH)/environment_variables.sh && $(PARENT_PATH)/operator/run_operator.sh"
+
+operator_odf: operator_common
+	@read -p "Did you add the required ODF disks (3 disks per worker)? [y/N] " confirm && if [ "$$confirm" != "y" ]; then \
+		echo "Please add the disks before proceeding."; \
+		exit 1; \
+	fi
+	@bash -c "source $(MAIN_PATH)/environment_variables.sh && $(PARENT_PATH)/operator/odf/run_odf.sh"
+
+operator_cnv: operator_common
+	@bash -c "source $(MAIN_PATH)/environment_variables.sh && $(PARENT_PATH)/operator/cnv/run_cnv.sh"
 
 test:
 	@if [ ! -f "$(MAIN_PATH)/environment_variables.sh" ]; then \
@@ -53,4 +65,6 @@ help:
 	@echo "Usage:"
 	@echo "  make cluster         - Create BareMetal cluster"
 	@echo "  make operator        - Install CNV/LSO/ODF operators [DATA DISK Required - 3 disks per worker!!!]"
+	@echo "  make operator_odf    - Install ODF operator [DATA DISK Required]"
+	@echo "  make operator_cnv    - Install CNV operator"
 	@echo "  make test            - Run Workloads (ensure test environments are configured and podman is installed): Results path: /tmp/benchmark-runner-run-artifacts"
